# Generated by Django 2.1.5 on 2019-01-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revista',
            old_name='nome',
            new_name='colecao',
        ),
        migrations.AddField(
            model_name='revista',
            name='amigo',
            field=models.ManyToManyField(to='core.Amigo'),
        ),
        migrations.AddField(
            model_name='revista',
            name='caixa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Caixa'),
        ),
        migrations.AlterField(
            model_name='amigo',
            name='grupo_amigo',
            field=models.CharField(choices=[('PREDIO', 'Prédio'), ('ESCOLA', 'Escola')], max_length=50),
        ),
    ]
