# Generated by Django 2.1.5 on 2019-01-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190108_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='nome_do_amigo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Amigo'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='numero_da_revista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Revista'),
        ),
    ]
