# Generated by Django 2.1.5 on 2019-01-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190108_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revista',
            name='amigo',
        ),
    ]
